### ISSUE TITLE
error while disabling

### ISSUE THREAD

**Issue by the456gamer** [ChickenStyle/FancyBags#3]
```
[13:57:14] [Server thread/INFO]: [FancyBags] Enabling FancyBags v1.5.3
[13:57:14] [Server thread/INFO]: FancyBags >>> This version isn't supported!
[13:57:14] [Server thread/INFO]: FancyBags >>> Plugin will be disabled!
[13:57:14] [Server thread/INFO]: [FancyBags] Disabling FancyBags v1.5.3
[13:57:14] [Server thread/ERROR]: Error occurred while disabling FancyBags v1.5.3 (Is it up to date?)
java.lang.NullPointerException: null
	at me.chickenstyle.Backpack.Configs.CustomBackpacks.getBackpacks(CustomBackpacks.java:67) ~[?:?]
	at me.chickenstyle.Backpack.Main.onDisable(Main.java:91) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:376) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at me.chickenstyle.Backpack.Main.getServerVersion(Main.java:166) ~[?:?]
	at me.chickenstyle.Backpack.Main.onEnable(Main.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:492) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:219) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[Server_spigot-1.16.2.jar:git-Spigot-379750e-9c9fb59]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
i think this is onDisable being called, and it access variables that havent been defined?

**Comment by ChickenStyle** [comment]
Yeah probably, because there is some stuff I define on onEnable, but it doesn't run because it disables the plugin, soo it's null
